### ISSUE TITLE
All requests 404

### ISSUE THREAD

**Issue by Paraknight** [fojas/cleverbot-node#11]
See here for more info: https://github.com/benmanns/cleverbot/issues/7

**Comment by Xaekai** [comment]
++

**Comment by dzek69** [comment]
i'm not much into github, so no pull request (looks like nobody will merge it anyway), no fork, just a gist with ugly solution:
https://gist.github.com/anonymous/e3cdd3bcb02552f002bc

that's all i could do, probably there's better library than built-in http, that can handle cookies automatically

i'd be nice if anyone can create a fork with this solution and then - keep this alive

**Comment by AvatarKava** [comment]
@dzek69 - I don't mind forking and putting in a PR for this, but I'm getting back just <html> when I attempt to use your provided gist.  Any ideas?

**Comment by dzek69** [comment]
i forgot to mention - you need to fire `prepare()` function after creating an object. This could be put in the constructor if anyone wants. I just wanted to make it work, I wasn't caring about proper coding, as this lib isn't proper-coded anyway.

```javascript
var bot = new Cleverbot();
bot.prepare();
bot.write('aaa');
bot.write('aaa');
bot.write('aaa');
// etc
```

**Comment by AvatarKava** [comment]
Think I've got this situated in #12 .  Thanks for the help @dzek69 !

**Comment by Jimbo1167** [comment]
++ on getting this fixed :)

**Comment by ishan-marikar** [comment]
Hope this gets fixed. Until then, I guess I'd have to use cleverbot.io *sigh*

**Comment by ishan-marikar** [comment]
I think it's an issue with [Cleverbot's API](http://www.cleverbot.com/webservicemin). I keep getting 404s when I try to access it directly.

**Comment by ishan-marikar** [comment]
This guy seems to have fixed it in pierredavidbelanger/chatter-bot-api#9. I'll try to see if I can get the module working again.

**Comment by trashken** [comment]
Great to hear this is getting looked at.

**Comment by fojas** [comment]
I have finally found some time to update the code. The biggest change here is that all code now needs to be passed to `Cleverbot.prepare` as a callback.
