### ISSUE TITLE
Problems with special characters

### ISSUE THREAD

**Issue by Fuechschen** [fojas/cleverbot-node#14]
In the german language, we have characters like ä, ö and ü. Cleverbot-node only returns some "random" characters for them.

**Comment by fojas** [comment]
@Fuechschen Sorry for the delayed response. I looked into this, but could not duplicate the issue. This seems to me that it may be an issue with your integration. I changed the code in the example folder to start with a german sentence and I was able to see characters with umlauts. Below is a sample that I pulled from running it and it seems fine.

```
Stan Sitwell  :  Das ist schön
Bob Loblaw  :  Und wie geht es dir.
Stan Sitwell  :  Mir geht es gut.
Bob Loblaw  :  Mir geht es auch gut:)Danke für die Nachfrage!♥.
Stan Sitwell  :  Was machst du gerade?
Bob Loblaw  :  Mit dir schreiben und du?
Stan Sitwell  :  Magst du mich?
Bob Loblaw  :  Ein bisschen, du mich?
Stan Sitwell  :  Jaq ein Bischen.
Bob Loblaw  :  Sag was auf englisch.
Stan Sitwell  :  Kannst du englisch sprechen?
Bob Loblaw  :  Ein bisschen.
Stan Sitwell  :  Sag mal was auf türkische.
```

**Comment by Fuechschen** [comment]
Maybe it was some issue with cleverbot itself and incomptible encodings. i highly doubt it was the integration since i haven't touched that code in ages...

Anyways, thanks for having a lokk at this
