### ISSUE TITLE
Returning 404

### ISSUE THREAD

**Issue by FranciscoG** [fojas/cleverbot-node#21]
Looks like Cleverbot API has changed or something because I'm getting a 404 response

```
{ message: '<html>',
  sessionid: '\n<head><title>404 Not Found</title></head>',
  logurl: '\n<body bgcolor="white">',
  vText8: '\n<center><h1>404 Not Found</h1></center>',
  vText7: '\n<hr><center>nginx/1.6.2 (Ubuntu)</center>',
  vText6: '\n</body>',
  vText5: '\n</html>',
  vText4: '\n' }
```

**Comment by avatarkava** [comment]
Have you done an update via npm to get the latest version?  This just got patched to fix some changes in cleverbot today.

**Comment by FranciscoG** [comment]
that fixed it,   thanks!!

I had tried a direct update of just the lib but it failed, so I got rid of my node_modules folder and npm installed everything again and that worked.  (I have cleverbot-node set to use "latest")

**Comment by fojas** [comment]
Good to hear!
