### ISSUE TITLE
404 Not Found?

### ISSUE THREAD

**Issue by Jwiggiff** [fojas/cleverbot-node#22]
`{ message: '<html>',
  sessionid: '\n<head><title>404 Not Found</title></head>',
  logurl: '\n<body bgcolor="white">',
  vText8: '\n<center><h1>404 Not Found</h1></center>',
  vText7: '\n<hr><center>nginx/1.6.2 (Ubuntu)</center>',
  vText6: '\n</body>',
  vText5: '\n</html>',
  vText4: '\n' }`

**Comment by fojas** [comment]
@Jwiggiff what version are you using? Since the cleverbot API is unreliable, only the latest version works. As of right now that is version 0.2.4.

**Comment by Jwiggiff** [comment]
@fojas i ran `npm view cleverbot-node version` and it said 0.2.4

**Comment by Jom3es12** [comment]
@fojas I'm getting the same issue. 
` var Cleverbot = require('cleverbot-node');
    cleverbot = new Cleverbot;
    Cleverbot.prepare(function(){
      cleverbot.write(cleverMessage, function (response) {
         console.log(response.message);
      });
    });`

returns just the <html> in the log.

**Comment by fojas** [comment]
@Jwiggiff, @Jom3es12 The problem described seems like the issue that was fixed with release 0.2.4. Is the latest change in your project? What is the result of running `grep "/webservicemin" ./node_modules/cleverbot-node/lib/cleverbot.js`? It should look like `path: '/webservicemin?uc=321&',`

**Comment by Jwiggiff** [comment]
i know this is really late but it says `'grep' is not recognized as an internal or external command`

**Comment by fojas** [comment]
Sorry. I assumed you had grep installed. There has been another version released since this issue was opened. Can you try updating to the latest version?

**Comment by Jwiggiff** [comment]
i just updated, when I run `npm view cleverbot-node version` it says 0.2.6, and it does not work.

**Comment by Jom3es12** [comment]
It seems to work just fine for me now, I can't remember what I did but it
works fine.

**Comment by Jwiggiff** [comment]
what version r u on @Jom3es12

**Comment by Jom3es12** [comment]
I'm on 0.2.6

**Comment by Jwiggiff** [comment]
@fojas ??

**Comment by Jom3es12** [comment]
Have you tried cleverbot.io?

**Comment by Jwiggiff** [comment]
@Jom3es12 I tried it but it was kind of wierd and I didn't like it. I really like this one. :)

**Comment by Jwiggiff** [comment]
Hey I fixed it! Basically my prepare function was empty then i had the write function later, I just put the write function in the prepare function and it worked.
