### ISSUE TITLE
Cleverbot API call now defunct

### ISSUE THREAD

**Issue by atallguy89** [fojas/cleverbot-node#26]
The path containing webservicemin (https://github.com/fojas/cleverbot-node/blob/master/lib/cleverbot.js#L78) is now defunct.

http://www.cleverbot.com/webservicemin?uc=3210& now returns a 404 page.

**Comment by CoreParadox** [comment]
I fixed it with my pull request. #27

**Comment by the2hill** [comment]
PR #27 lets the call through, but now the response message is always empty?

**Comment by CoreParadox** [comment]
Hm. I'm not experiencing that
