### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by PixelGGamer** [fojas/cleverbot-node#28]
After few days of working, now I can't do any requests, even with API key.
Any idea why this happens?
Logs:

`{ message: '<html>',
  sessionid: '\n<head><title>401 Authorization Required</title></head>',
  logurl: '\n<body bgcolor="white">',
  vText8: '\n<center><h1>401 Authorization Required</h1></center>',
  vText7: '\n<hr><center>nginx/1.6.2 (Ubuntu)</center>',
  vText6: '\n</body>',
  vText5: '\n</html>',
  vText4: '\n' }`

**Comment by fojas** [comment]
There are now 2 new versions of this package. One each for the official and unofficial APIs. The `0.2.x` versions will be the unofficial API. and the `0.3.x` versions will be the official API.
