### ISSUE TITLE
Unexpected token in json

### ISSUE THREAD

**Issue by 27therealone** [fojas/cleverbot-node#32]
So sometimes my bot errors with unexpected token found in JSON... Error can be found here
https://sentry.io/share/issue/3133353338302e323234363239343030/

**Comment by shantanuthatte** [comment]
I'm experiencing the same issue too.

**Comment by 27therealone** [comment]
I added a pull request to fix that problem. Just a simple backslash remover function xD

**Comment by Zerss** [comment]
Got the same problem here, tried using your pull req but it doesn't work for me ( /\/s aren't accepted for me, tried using /\\/s but doesn't work either). Managed to do it by doing a simple .split('\\').join(' ') which is weird, but which works.

**Comment by fojas** [comment]
Sorry. I might not have time to push a new release to npm today.

Do you have a copy of the JSON that is failing? I wonder if I can submit it to the folks at Cleverbot to see if their API is returning malformed JSON. 

Thanks!

**Comment by Zerss** [comment]
There you go. http://pastebin.com/rmGRGjYY

**Comment by Zerss** [comment]
Also found out that -logically- Cleverbot doesn't like when we're using "s. Adding a replace for them in the message part could be wiser.

**Comment by 27therealone** [comment]
Oh yes i'm an idiot /\/ won't work as theres a word before, /W/ should do it as it finds a non-word character...

**Comment by shantanuthatte** [comment]
Testing this out.. It also sometimes breaks on the new emojis.. *Needs more testing*

From the string `\test\\\.` I can say that the JSON returned is not escaped for `input` and successive fields. *Maybe* Cleverbot can fix this?

**Comment by fojas** [comment]
I pushed a new version that I think should fix it. Please try now.
