### ISSUE TITLE
Unexpected token in json due to emojis

### ISSUE THREAD

**Issue by Edsardio** [fojas/cleverbot-node#34]
SyntaxError: Unexpected token ♂ in JSON at position 2062

It seems to crash sometimes due to symbols/emoji's etc.

**Comment by fojas** [comment]
What version of the package are you using? It say in node_modules/cleverbot-node/package.json. Version 0.3.5 should work.

**Comment by Edsardio** [comment]
Using version 3.5 that's why I was surprised

**Comment by fojas** [comment]
I just ran the code in `examples/sample.js` and replaced the initial test message with `♂🎅🏾` and it worked. Are you able to capture what the request or JSON response is from the API?

**Comment by Edsardio** [comment]
Hmm weird, after having it talk to itself for aprox 5 minutes it's not crashing anymore... Exact same code as when I created this issue...
