### ISSUE TITLE
Error handling 

### ISSUE THREAD

**Issue by bobland1** [fojas/cleverbot-node#35]
At the comment I'm using the try and catch method. But it still errors and crashes. It's a JSON error... I'm guessing this is fixed in the newest release

**Comment by fojas** [comment]
I'm not sure I understad the issue. Do you have examples of what you are doing and what is going wrong?

**Comment by CharlotteDunois** [comment]
The process exits when there is an error while trying to parsing the JSON response. Putting `cleverbot.write` inside a try-catch block doesn't catch the error. Please put JSON response parsing into a try-catch block.

**Comment by fojas** [comment]
I added an errorCallback argument to the write function. I don't want to make assumptions about how users want to handle errors. If an error occurs, the callback is called and the write function just returns without continuing. I hope that is enough.

Thanks!
