### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by kohltastrophe** [fojas/cleverbot-node#38]
In cleverbot.js you have an issue on line 58 where the eval will error without catching it, halting the program.

This can be fixed by changing line 58 from:
`eval("responseBody = " + body)`
to:
`try {eval("responseBody = " + body)} catch(e) {console.log(e)}`

**AND** changing line 60-61 from:
```
responseBody.message = responseBody.output;
this.state = responseBody.cs;
```
to:
```
try {
responseBody.message = responseBody.output;
this.state = responseBody.cs;
} catch(e) {console.log(e)}
```

Thanks for the great package otherwise!

**Comment by fojas** [comment]
I added an `errorCallback` argument to the `write` function. I don't want to make assumptions about how users want to handle errors. If an error occurs, the callback is called and the write function just returns without continuing. I hope that is enough.

Thanks!

**Comment by kohltastrophe** [comment]
Even better than my temporary fix, keep up the good work!
