### ISSUE TITLE
API requests are denied by cleverbot

### ISSUE THREAD

**Issue by dpritchett** [fojas/cleverbot-node#9]
Bob Loblaw  :  

``` json
{ message: '',
  sessionid: 'DENIED',
  logurl: '',
  vText8: '',
  vText7: '',
  vText6: '',
  vText5: '',
  vText4: '',
  vText3: '',
  vText2: '',
  prevref: '',
  '': '',
  emotionalhistory: '',
  ttsLocMP3: '',
  ttsLocTXT: '',
  ttsLocTXT3: '',
  ttsText: '',
  lineref: '',
  lineURL: '',
  linePOST: '',
  lineChoices: '',
  lineChoicesAbbrev: '',
  typingData: '',
  divert: '' }
```

**Comment by dtesler** [comment]
Are you receiving 403s?

I occasionally get this when using this specific library, I end up waiting a bit and it's back to normal.  It's possible that if you're using this a lot cleverbot may try to block you.

You could also try using the [cleverbot.io](https://cleverbot.io) node.js library.  As to my knowledge this hasn't happened here yet.
